'''
	This script is used to filter a list of commits to only keep those 
	having in the message at least one token from tokens list.
	It takes in argument one JSON file containing commits (JSON file generated by retrieveCommitsFromRepo.sh script !)
	It takes also a list of tokens for the filtering, strings delimited by "," without space
	It takes also the output JSON file name to store the result. We decided this in order to be independant of OS (windows vs macos vs linux)

	It produces a JSON file associating to each filtered (keeped) commit's message to to cmmit sha :
	{"commit message containing a token" : "sha"}

	RUN : python3 filterCommitsByTokens.py ../jsons/thinksBoard.json token1,token2,token3 outputFileName.JSON
'''

import sys
import json

if ( len(sys.argv) < 4 ) :
	print("Give JSON data file and filtering tokens as argument :\n python3 filterCommitsByTokens.py ../jsons/thinksBoard.json token1,token2,token3 outputFileName.JSON")
else :
	tokens = sys.argv[2].split(',')
	outputFileName = sys.argv[3]
	jsonOutput = {}

	print("Filtering "+sys.argv[1]+" commits JSON file by tokens : ", tokens)

	#tokens = ['environment', 'variable', 'env', 'var']
	with open(sys.argv[1], 'r') as f :
		logs_json = json.load(f)

	for log in logs_json :
		if any(token in log['subject'] for token in tokens) :
			print(log['subject']+ "   :   " + log['sha'])
			jsonOutput[log['subject']] = log['sha']

	with open(outputFileName, 'w') as outputFile:
		json.dump(jsonOutput, outputFile)