'''
	This script is used to filter a list of commits to only keep those 
	having in the message at least one token from tokens list.
	It takes in argument one JSON file containing commits (JSON file generated by retrieveCommitsFromRepo.sh script !)
	It takes also a list of tokens for the filtering, strings delimited by "," without space

	RUN : python3 filterCommitsByTokens.py ../jsons/thinksBoard.json token1,token2,token3
'''

import sys
import json

if ( len(sys.argv) < 3 ) :
	print("Give JSON data file and filtering tokens as argument :\n python3 filterCommitsByTokens.py ../jsons/thinksBoard.json token1,token2,token3")
else :
	tokens = sys.argv[2].split(',')

	print("Filtering "+sys.argv[1]+" commits JSON file by tokens : ", tokens)

	#tokens = ['environment', 'variable', 'env', 'var']
	with open(sys.argv[1], 'r') as f :
		logs_json = json.load(f)

	for log in logs_json :
		if any(token in log['subject'] for token in tokens) :
			print(log['subject']+ "   :   " + log['sha'])