'''
	This script is used to filter a list of commits to only keep those 
	having in the message at least one token from tokens list.
	It takes in argument one JSON file containing commits (JSON file generated by retrieveCommitsFromRepo.sh script !)
	
	RUN : python3 scriptPython.py ../jsons/thinksBoard.json
'''

import sys
import json

if ( len(sys.argv) < 2 ) :
	print("Give JSON data file as argument :\n python3 scriptPython.py ../jsons/thinksBoard.json")
else :
	tokens = ['environment', 'variable', 'env', 'var']
	with open(sys.argv[1], 'r') as f :
		logs_json = json.load(f)

	for log in logs_json :
		if any(token in log['subject'] for token in tokens) :
			print(log['subject']+ "   :   " + log['sha'])